name: ðŸ› Bug Report
description: Submit a bug report
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: >
        ðŸ’¼ [CosmoCode](https://www.cosmocode.de) is a software company in Berlin providing services for wiki,
        app and web development. We're happy to release some of our work as Open Source, but please be aware
        that **we are not able to provide free support**.


        ðŸ›‘ As such we can't guarantee quick responses for bug reports opened on our Open Source projects.


        ðŸ¤ If you require certain features or bugs fixed, you can always **hire us**.
        Feel free to contact us at info@cosmocode.de for a custom offer.

        âš›ï¸ **DokuWiki users:** Join our 
        [DokuWiki Business Plugin Partner Program](https://www.cosmocode.de/en/services/wiki/dokuwiki-partnership/)
        for guaranteed and quick feedback
        

        ---
  - type: textarea
    attributes:
      label: Issue Description
      description: >-
        Describe the issue you are experiencing below. Basically tell us

          * What you were trying to do
          * What you expected to happen
          * What actually happened

        Provide a clear and concise description of what the problem is and include as many
        details as possible. For example:
        
          * error messages and log files
          * screenshots or videos to explain the problem
          * infos about your environment (e.g. browser, operating system, device)
          * messages from your browser's error console if applicable
    validations:
      required: true
